"""initial_schema_com_campos_fsrs

Revision ID: 3c1a7670028f
Revises: 
Create Date: 2026-03-08 10:49:38.428233

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c1a7670028f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alunos',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('senha_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('admin', 'aluno', name='role_enum'), nullable=False),
    sa.Column('nivel_desafio', sa.Enum('conservador', 'moderado', 'agressivo', name='nivel_desafio_enum'), nullable=False),
    sa.Column('horas_por_dia', sa.Float(), nullable=True),
    sa.Column('dias_por_semana', sa.Float(), nullable=True),
    sa.Column('area', sa.String(length=100), nullable=True),
    sa.Column('banca', sa.String(length=100), nullable=True),
    sa.Column('cargo', sa.String(length=200), nullable=True),
    sa.Column('data_prova', sa.DateTime(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('alunos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_alunos_email'), ['email'], unique=True)

    op.create_table('config_sistema',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('chave', sa.String(length=100), nullable=False),
    sa.Column('valor', sa.Text(), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('config_sistema', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_config_sistema_chave'), ['chave'], unique=True)

    op.create_table('topicos',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('parent_id', sa.String(length=36), nullable=True),
    sa.Column('nivel', sa.Integer(), nullable=True),
    sa.Column('nome', sa.String(length=300), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('area', sa.String(length=100), nullable=True),
    sa.Column('banca', sa.String(length=100), nullable=True),
    sa.Column('peso_edital', sa.Float(), nullable=True),
    sa.Column('decay_rate', sa.Float(), nullable=True),
    sa.Column('dependencias_json', sa.Text(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['topicos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cronogramas',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('aluno_id', sa.String(length=36), nullable=False),
    sa.Column('modo', sa.Enum('pre_prova', 'revisao_final', name='modo_cronograma_enum'), nullable=False),
    sa.Column('modo_revisao_final', sa.Boolean(), nullable=True),
    sa.Column('data_ativacao_revisao', sa.DateTime(), nullable=True),
    sa.Column('edital_json', sa.Text(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['aluno_id'], ['alunos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cronogramas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cronogramas_aluno_id'), ['aluno_id'], unique=False)

    op.create_table('erros_criticos',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('aluno_id', sa.String(length=36), nullable=False),
    sa.Column('topico_id', sa.String(length=36), nullable=True),
    sa.Column('id_bateria', sa.String(length=100), nullable=True),
    sa.Column('materia', sa.String(length=200), nullable=True),
    sa.Column('topico_texto', sa.String(length=500), nullable=True),
    sa.Column('qtd_erros', sa.Integer(), nullable=True),
    sa.Column('observacao', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('pendente', 'em_revisao', 'resolvido', name='erro_status_enum'), nullable=False),
    sa.Column('data', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['aluno_id'], ['alunos.id'], ),
    sa.ForeignKeyConstraint(['topico_id'], ['topicos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('erros_criticos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_erros_criticos_aluno_id'), ['aluno_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_erros_criticos_topico_id'), ['topico_id'], unique=False)

    op.create_table('metas_semanais',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('aluno_id', sa.String(length=36), nullable=False),
    sa.Column('janela_inicio', sa.DateTime(), nullable=False),
    sa.Column('janela_fim', sa.DateTime(), nullable=False),
    sa.Column('nivel', sa.Enum('conservador', 'moderado', 'agressivo', name='nivel_meta_enum'), nullable=False),
    sa.Column('carga_meta_min', sa.Integer(), nullable=True),
    sa.Column('carga_realizada_min', sa.Integer(), nullable=True),
    sa.Column('deficit_min', sa.Integer(), nullable=True),
    sa.Column('encerrada', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['aluno_id'], ['alunos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('metas_semanais', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_metas_semanais_aluno_id'), ['aluno_id'], unique=False)

    op.create_table('padroes_cognitivos',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('aluno_id', sa.String(length=36), nullable=False),
    sa.Column('tipo', sa.Enum('excecao', 'dupla_negativa', 'aplicacao', 'conceito', 'comparacao', name='padrao_tipo_enum'), nullable=False),
    sa.Column('confianca', sa.Float(), nullable=True),
    sa.Column('total_erros_analisados', sa.Integer(), nullable=True),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.Column('detectado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['aluno_id'], ['alunos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('padroes_cognitivos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_padroes_cognitivos_aluno_id'), ['aluno_id'], unique=False)

    op.create_table('proficiencias',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('aluno_id', sa.String(length=36), nullable=False),
    sa.Column('topico_id', sa.String(length=36), nullable=True),
    sa.Column('id_bateria', sa.String(length=100), nullable=True),
    sa.Column('materia', sa.String(length=200), nullable=True),
    sa.Column('subtopico', sa.String(length=300), nullable=True),
    sa.Column('acertos', sa.Integer(), nullable=True),
    sa.Column('total', sa.Integer(), nullable=True),
    sa.Column('percentual', sa.Float(), nullable=True),
    sa.Column('fonte', sa.Enum('qconcursos', 'tec', 'prova_anterior_mesma_banca', 'prova_anterior_outra_banca', 'simulado', 'quiz_ia', 'manual', 'calibracao', 'curso', name='fonte_enum'), nullable=False),
    sa.Column('peso_fonte', sa.Float(), nullable=True),
    sa.Column('data', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['aluno_id'], ['alunos.id'], ),
    sa.ForeignKeyConstraint(['topico_id'], ['topicos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('proficiencias', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_proficiencias_aluno_id'), ['aluno_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_proficiencias_topico_id'), ['topico_id'], unique=False)

    op.create_table('sessoes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('aluno_id', sa.String(length=36), nullable=False),
    sa.Column('topico_id', sa.String(length=36), nullable=True),
    sa.Column('cronograma_id', sa.String(length=36), nullable=True),
    sa.Column('tipo', sa.Enum('teoria_pdf', 'exercicios', 'video', 'flashcard_texto', 'calibracao', name='tipo_sessao_enum'), nullable=False),
    sa.Column('duracao_planejada_min', sa.Integer(), nullable=True),
    sa.Column('duracao_real_min', sa.Integer(), nullable=True),
    sa.Column('confianca', sa.Enum('baixa', 'media', 'alta', name='confianca_enum'), nullable=False),
    sa.Column('stability', sa.Float(), nullable=True),
    sa.Column('difficulty', sa.Float(), nullable=True),
    sa.Column('uma_vez', sa.Boolean(), nullable=True),
    sa.Column('concluida', sa.Boolean(), nullable=True),
    sa.Column('data_agendada', sa.DateTime(), nullable=True),
    sa.Column('data_concluida', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['aluno_id'], ['alunos.id'], ),
    sa.ForeignKeyConstraint(['cronograma_id'], ['cronogramas.id'], ),
    sa.ForeignKeyConstraint(['topico_id'], ['topicos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sessoes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sessoes_aluno_id'), ['aluno_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sessoes_topico_id'), ['topico_id'], unique=False)

    op.create_table('simulados',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('aluno_id', sa.String(length=36), nullable=False),
    sa.Column('edital_id', sa.String(length=36), nullable=True),
    sa.Column('cronograma_id', sa.String(length=36), nullable=True),
    sa.Column('questoes_json', sa.Text(), nullable=True),
    sa.Column('resultado_json', sa.Text(), nullable=True),
    sa.Column('total_questoes', sa.Integer(), nullable=True),
    sa.Column('acertos', sa.Integer(), nullable=True),
    sa.Column('percentual', sa.Float(), nullable=True),
    sa.Column('concluido', sa.Boolean(), nullable=True),
    sa.Column('data_inicio', sa.DateTime(), nullable=True),
    sa.Column('data_fim', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['aluno_id'], ['alunos.id'], ),
    sa.ForeignKeyConstraint(['cronograma_id'], ['cronogramas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('simulados', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_simulados_aluno_id'), ['aluno_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('simulados', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_simulados_aluno_id'))

    op.drop_table('simulados')
    with op.batch_alter_table('sessoes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sessoes_topico_id'))
        batch_op.drop_index(batch_op.f('ix_sessoes_aluno_id'))

    op.drop_table('sessoes')
    with op.batch_alter_table('proficiencias', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_proficiencias_topico_id'))
        batch_op.drop_index(batch_op.f('ix_proficiencias_aluno_id'))

    op.drop_table('proficiencias')
    with op.batch_alter_table('padroes_cognitivos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_padroes_cognitivos_aluno_id'))

    op.drop_table('padroes_cognitivos')
    with op.batch_alter_table('metas_semanais', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_metas_semanais_aluno_id'))

    op.drop_table('metas_semanais')
    with op.batch_alter_table('erros_criticos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_erros_criticos_topico_id'))
        batch_op.drop_index(batch_op.f('ix_erros_criticos_aluno_id'))

    op.drop_table('erros_criticos')
    with op.batch_alter_table('cronogramas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cronogramas_aluno_id'))

    op.drop_table('cronogramas')
    op.drop_table('topicos')
    with op.batch_alter_table('config_sistema', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_config_sistema_chave'))

    op.drop_table('config_sistema')
    with op.batch_alter_table('alunos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_alunos_email'))

    op.drop_table('alunos')
    # ### end Alembic commands ###
