"""add banca to proficiencia

Revision ID: 4c988fda59af
Revises: 56abb589120d
Create Date: 2026-03-28 13:48:20.384838

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c988fda59af'
down_revision: Union[str, None] = '56abb589120d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('proficiencias', schema=None) as batch_op:
        batch_op.add_column(sa.Column('banca', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('proficiencias', schema=None) as batch_op:
        batch_op.drop_column('banca')

    # ### end Alembic commands ###
