"""add sessao_estudo

Revision ID: 56abb589120d
Revises: u1v2w3x4y5z6
Create Date: 2026-03-28 13:46:11.476379

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '56abb589120d'
down_revision: Union[str, None] = 'u1v2w3x4y5z6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sessoes_estudo',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('aluno_id', sa.String(length=36), nullable=False),
    sa.Column('subtopico_id', sa.String(length=36), nullable=True),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('duracao_min', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['aluno_id'], ['alunos.id'], ),
    sa.ForeignKeyConstraint(['subtopico_id'], ['topicos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sessoes_estudo', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sessoes_estudo_aluno_id'), ['aluno_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sessoes_estudo_subtopico_id'), ['subtopico_id'], unique=False)

    # Drop na ordem correta: filhos antes dos pais (evita erro de FK/índice dependente)
    with op.batch_alter_table('task_video_avaliacoes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_task_video_avaliacoes_aluno_id'))
        batch_op.drop_index(batch_op.f('ix_task_video_avaliacoes_video_id'))

    op.drop_table('task_video_avaliacoes')
    with op.batch_alter_table('task_videos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_task_videos_task_code'))

    op.drop_table('task_videos')
    with op.batch_alter_table('study_tasks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_study_tasks_aluno_id'))
        batch_op.drop_index(batch_op.f('ix_study_tasks_goal_id'))
        batch_op.drop_index(batch_op.f('ix_study_tasks_task_code'))

    op.drop_table('study_tasks')
    with op.batch_alter_table('task_conteudo', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_task_conteudo_subtopico_id'))
        batch_op.drop_index(batch_op.f('ix_task_conteudo_task_code'))

    op.drop_table('task_conteudo')
    with op.batch_alter_table('metas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_metas_aluno_id'))

    op.drop_table('metas')
    with op.batch_alter_table('explicacoes_subtopico', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_explicacoes_subtopico_topico_id'))

    op.drop_table('explicacoes_subtopico')
    with op.batch_alter_table('subtopico_estados', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_subtopico_estados_aluno_id'))
        batch_op.drop_index(batch_op.f('ix_subtopico_estados_subtopico_id'))

    op.drop_table('subtopico_estados')
    # Remove FK de perfil_estudo antes de dropar planos_base
    with op.batch_alter_table('perfil_estudo', schema=None) as batch_op:
        batch_op.drop_column('plano_base_id')
    op.drop_table('planos_base')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('perfil_estudo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('plano_base_id', sa.VARCHAR(length=36), nullable=True))

    op.create_table('subtopico_estados',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('aluno_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('subtopico_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('estado', sa.VARCHAR(length=20), server_default=sa.text("'novo'"), nullable=False),
    sa.Column('exposure_count', sa.INTEGER(), server_default=sa.text("'0'"), nullable=False),
    sa.Column('accuracy_rate', sa.FLOAT(), server_default=sa.text("'0.0'"), nullable=False),
    sa.Column('ultima_exposicao', sa.DATETIME(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['aluno_id'], ['alunos.id'], ),
    sa.ForeignKeyConstraint(['subtopico_id'], ['topicos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('aluno_id', 'subtopico_id', name=op.f('uq_subtopico_estado_aluno'))
    )
    with op.batch_alter_table('subtopico_estados', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_subtopico_estados_subtopico_id'), ['subtopico_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_subtopico_estados_aluno_id'), ['aluno_id'], unique=False)

    op.create_table('planos_base',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('area', sa.VARCHAR(length=100), nullable=False),
    sa.Column('perfil', sa.VARCHAR(length=50), nullable=False),
    sa.Column('versao', sa.INTEGER(), nullable=False),
    sa.Column('gerado_por_ia', sa.BOOLEAN(), nullable=False),
    sa.Column('revisado_admin', sa.BOOLEAN(), nullable=False),
    sa.Column('ativo', sa.BOOLEAN(), nullable=False),
    sa.Column('fases_json', sa.TEXT(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('task_video_avaliacoes',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('video_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('aluno_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('nota', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['aluno_id'], ['alunos.id'], name=op.f('fk_avaliacao_aluno_id')),
    sa.ForeignKeyConstraint(['video_id'], ['task_videos.id'], name=op.f('fk_avaliacao_video_id')),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('video_id', 'aluno_id', name=op.f('uq_avaliacao_video_aluno'))
    )
    with op.batch_alter_table('task_video_avaliacoes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_task_video_avaliacoes_video_id'), ['video_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_task_video_avaliacoes_aluno_id'), ['aluno_id'], unique=False)

    op.create_table('task_videos',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('task_code', sa.VARCHAR(length=20), nullable=False),
    sa.Column('titulo', sa.VARCHAR(length=300), nullable=False),
    sa.Column('url', sa.VARCHAR(length=500), nullable=False),
    sa.Column('descricao', sa.TEXT(), nullable=True),
    sa.Column('avaliacao_media', sa.FLOAT(), nullable=True),
    sa.Column('total_avaliacoes', sa.INTEGER(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['task_code'], ['task_conteudo.task_code'], name=op.f('fk_task_videos_task_code')),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('task_videos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_task_videos_task_code'), ['task_code'], unique=False)

    op.create_table('task_conteudo',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('task_code', sa.VARCHAR(length=20), nullable=False),
    sa.Column('subtopico_id', sa.VARCHAR(length=36), nullable=True),
    sa.Column('tipo', sa.VARCHAR(length=30), nullable=False),
    sa.Column('objetivo', sa.TEXT(), nullable=True),
    sa.Column('instrucoes', sa.TEXT(), nullable=True),
    sa.Column('conteudo_pdf', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['subtopico_id'], ['topicos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('subtopico_id', 'tipo', name=op.f('uq_task_conteudo_subtopico_tipo'))
    )
    with op.batch_alter_table('task_conteudo', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_task_conteudo_task_code'), ['task_code'], unique=1)
        batch_op.create_index(batch_op.f('ix_task_conteudo_subtopico_id'), ['subtopico_id'], unique=False)

    op.create_table('explicacoes_subtopico',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('topico_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('content', sa.TEXT(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['topico_id'], ['topicos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('topico_id', name=op.f('uq_explicacao_topico'))
    )
    with op.batch_alter_table('explicacoes_subtopico', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_explicacoes_subtopico_topico_id'), ['topico_id'], unique=False)

    op.create_table('metas',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('aluno_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('numero_semana', sa.INTEGER(), nullable=False),
    sa.Column('tasks_meta', sa.INTEGER(), nullable=False),
    sa.Column('tasks_concluidas', sa.INTEGER(), server_default=sa.text("'0'"), nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), server_default=sa.text("'aberta'"), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['aluno_id'], ['alunos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('metas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_metas_aluno_id'), ['aluno_id'], unique=False)

    op.create_table('study_tasks',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('aluno_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('subject_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('topic_id', sa.VARCHAR(length=36), nullable=True),
    sa.Column('subtopic_id', sa.VARCHAR(length=36), nullable=True),
    sa.Column('tipo', sa.VARCHAR(length=12), nullable=False),
    sa.Column('status', sa.VARCHAR(length=11), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('questoes_json', sa.TEXT(), nullable=True),
    sa.Column('task_code', sa.VARCHAR(length=20), nullable=True),
    sa.Column('numero_cronograma', sa.INTEGER(), nullable=True),
    sa.Column('week_number', sa.INTEGER(), nullable=True),
    sa.Column('order_in_week', sa.INTEGER(), nullable=True),
    sa.Column('goal_id', sa.VARCHAR(length=36), nullable=True),
    sa.ForeignKeyConstraint(['aluno_id'], ['alunos.id'], ),
    sa.ForeignKeyConstraint(['goal_id'], ['metas.id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['topicos.id'], ),
    sa.ForeignKeyConstraint(['subtopic_id'], ['topicos.id'], ),
    sa.ForeignKeyConstraint(['task_code'], ['task_conteudo.task_code'], name=op.f('fk_study_tasks_task_code')),
    sa.ForeignKeyConstraint(['topic_id'], ['topicos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('study_tasks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_study_tasks_task_code'), ['task_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_study_tasks_goal_id'), ['goal_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_study_tasks_aluno_id'), ['aluno_id'], unique=False)

    with op.batch_alter_table('sessoes_estudo', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sessoes_estudo_subtopico_id'))
        batch_op.drop_index(batch_op.f('ix_sessoes_estudo_aluno_id'))

    op.drop_table('sessoes_estudo')
    # ### end Alembic commands ###
