"""limpar_enum_tipo_task

Revision ID: 6221168b67ff
Revises: 4710bbb33a30
Create Date: 2026-03-16 00:16:32.398670

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6221168b67ff'
down_revision: Union[str, None] = '4710bbb33a30'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alunos', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=sa.VARCHAR(length=7),
               type_=sa.Enum('administrador', 'mentor', 'estudante', name='role_enum'),
               existing_nullable=False)
        batch_op.alter_column('diagnostico_pendente',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('0'))

    with op.batch_alter_table('study_tasks', schema=None) as batch_op:
        batch_op.alter_column('tipo',
               existing_type=sa.VARCHAR(length=11),
               type_=sa.Enum('diagnostico', 'teoria', 'revisao', 'questionario', 'simulado', 'reforco', name='study_task_tipo_enum'),
               existing_nullable=False)
        batch_op.drop_index(batch_op.f('ix_study_tasks_subtopic_id'))
        batch_op.create_foreign_key('fk_study_tasks_task_code', 'task_conteudo', ['task_code'], ['task_code'])

    with op.batch_alter_table('subtopico_estados', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_subtopico_estado_aluno', ['aluno_id', 'subtopico_id'])

    with op.batch_alter_table('task_conteudo', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_task_conteudo_task_code'), type_='unique')
        batch_op.drop_index(batch_op.f('ix_task_conteudo_task_code'))
        batch_op.create_index(batch_op.f('ix_task_conteudo_task_code'), ['task_code'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task_conteudo', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_task_conteudo_task_code'))
        batch_op.create_index(batch_op.f('ix_task_conteudo_task_code'), ['task_code'], unique=False)
        batch_op.create_unique_constraint(batch_op.f('uq_task_conteudo_task_code'), ['task_code'])

    with op.batch_alter_table('subtopico_estados', schema=None) as batch_op:
        batch_op.drop_constraint('uq_subtopico_estado_aluno', type_='unique')

    with op.batch_alter_table('study_tasks', schema=None) as batch_op:
        batch_op.drop_constraint('fk_study_tasks_task_code', type_='foreignkey')
        batch_op.create_index(batch_op.f('ix_study_tasks_subtopic_id'), ['subtopic_id'], unique=False)
        batch_op.alter_column('tipo',
               existing_type=sa.Enum('diagnostico', 'teoria', 'revisao', 'questionario', 'simulado', 'reforco', name='study_task_tipo_enum'),
               type_=sa.VARCHAR(length=11),
               existing_nullable=False)

    with op.batch_alter_table('alunos', schema=None) as batch_op:
        batch_op.alter_column('diagnostico_pendente',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('role',
               existing_type=sa.Enum('administrador', 'mentor', 'estudante', name='role_enum'),
               type_=sa.VARCHAR(length=7),
               existing_nullable=False)

    # ### end Alembic commands ###
